"""Canonical standard Baja vehicle values used by all public runners."""

STANDARD_MINIMUM_CVT_RATIO = 0.9
STANDARD_MAXIMUM_CVT_RATIO = 3.5
STANDARD_FINAL_DRIVE_RATIO = 7.556
STANDARD_TIRE_DIAMETER_IN = 22.0
STANDARD_WHEEL_RADIUS_IN = STANDARD_TIRE_DIAMETER_IN / 2.0
STANDARD_INTEGRATION_STEP_S = 0.001
